#!/usr/bin/env bash
# Regenerates the design preview's data from the app's own classes.
#
# Both exporters run against the real Layout, BuddyTheme and Art, so the preview cannot
# drift from the build. Run this after changing any of them.
#
# Usage: tools/buildpreview.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CACHE="$ROOT/tools/.cache"
JAR="$CACHE/android-all.jar"
OUT="$CACHE/classes"
PREVIEW="$ROOT/tools/preview"

# check.sh rebuilds $OUT from scratch, so it has to run before the exporters compile.
"$ROOT/tools/check.sh" --quiet

javac --release 17 -classpath "$JAR:$OUT" -implicit:none -nowarn -d "$OUT" \
      "$ROOT/tools/ExportArt.java" "$ROOT/tools/ExportScreens.java" 2>&1 | grep -v '^Picked up' || true

java -cp "$JAR:$OUT" com.morningmission.app.ExportArt "$PREVIEW/art.json" | grep -v '^Picked up'
java -cp "$JAR:$OUT" com.morningmission.app.ExportScreens "$PREVIEW/screens.json" | grep -v '^Picked up'

python3 - "$PREVIEW" "$ROOT" <<'PYEOF'
import json, sys, os
preview, root = sys.argv[1], sys.argv[2]
art = json.load(open(os.path.join(preview, "art.json")))
screens = json.load(open(os.path.join(preview, "screens.json")))
merged = dict(screens)
merged["art"] = art
merged["buddies"] = art["buddies"]

# The colour each illustrated background is extended upward with. Scene samples the
# artwork's top row at runtime; computing it here keeps the preview identical without
# reading pixels in the browser, which a file:// page is not allowed to do.
try:
    from PIL import Image

    def top_row(path):
        im = Image.open(path).convert("RGB")
        w = im.width
        step = max(1, w // 16)
        px = [im.getpixel((x, 0)) for x in range(0, w, step)]
        return "#%02X%02X%02X" % tuple(sum(c[i] for c in px) // len(px) for i in range(3))

    drawable = os.path.join(root, "app/src/main/res/drawable-nodpi")
    merged["homeBackdropSky"] = top_row(os.path.join(drawable, "bg_home_storybook.png"))
    for i, b in enumerate(merged["buddies"]):
        merged["environments"][i]["backdropSky"] = top_row(
            os.path.join(drawable, "bg_adventure_%s.png" % b["key"]))
except Exception as exc:                       # a preview without it still renders
    print("buildpreview: could not sample backdrop skies (%s)" % exc)

assert all("index" in b for b in merged["buddies"]), "buddy index missing from the art export"
assert len(merged["environments"]) == len(merged["buddies"]), "an environment per buddy"
with open(os.path.join(preview, "data.js"), "w") as fh:
    fh.write("/* GENERATED by tools/buildpreview.sh -- do not edit. */\nconst DATA = "
             + json.dumps(merged, separators=(",", ":")) + ";\n")
print("buildpreview: data.js rebuilt (%d buddies, %d devices, %d activities, %d glyphs)"
      % (len(merged["buddies"]), len(merged["devices"]),
         len(merged["art"]["activities"]), len(merged["art"]["glyphs"])))
PYEOF

for f in data.js screens-engine.js screens-draw.js screens-ui.js; do
  node --check "$PREVIEW/$f"
done
echo "buildpreview: OK"
