#!/usr/bin/env bash
# Regenerates the design preview's data from the app's own classes.
#
# Both exporters run against the real Layout, BuddyTheme and Art, so the preview cannot
# drift from the build. Run this after changing any of them.
#
# Usage: tools/buildpreview.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CACHE="$ROOT/tools/.cache"
JAR="$CACHE/android-all.jar"
OUT="$CACHE/classes"
PREVIEW="$ROOT/tools/preview"

# check.sh rebuilds $OUT from scratch, so it has to run before the exporters compile.
"$ROOT/tools/check.sh" --quiet

javac --release 17 -classpath "$JAR:$OUT" -implicit:none -nowarn -d "$OUT" \
      "$ROOT/tools/ExportArt.java" "$ROOT/tools/ExportScreens.java" 2>&1 | grep -v '^Picked up' || true

java -cp "$JAR:$OUT" com.morningmission.app.ExportArt "$PREVIEW/art.json" | grep -v '^Picked up'
java -cp "$JAR:$OUT" com.morningmission.app.ExportScreens "$PREVIEW/screens.json" | grep -v '^Picked up'

python3 - "$PREVIEW" <<'PYEOF'
import json, sys, os
preview = sys.argv[1]
art = json.load(open(os.path.join(preview, "art.json")))
screens = json.load(open(os.path.join(preview, "screens.json")))
merged = dict(screens)
merged["art"] = art
merged["buddies"] = art["buddies"]
assert all("index" in b for b in merged["buddies"]), "buddy index missing from the art export"
assert len(merged["environments"]) == len(merged["buddies"]), "an environment per buddy"
with open(os.path.join(preview, "data.js"), "w") as fh:
    fh.write("/* GENERATED by tools/buildpreview.sh -- do not edit. */\nconst DATA = "
             + json.dumps(merged, separators=(",", ":")) + ";\n")
print("buildpreview: data.js rebuilt (%d buddies, %d devices, %d activities, %d glyphs)"
      % (len(merged["buddies"]), len(merged["devices"]),
         len(merged["art"]["activities"]), len(merged["art"]["glyphs"])))
PYEOF

for f in data.js screens-engine.js screens-draw.js screens-ui.js; do
  node --check "$PREVIEW/$f"
done
echo "buildpreview: OK"
