#!/usr/bin/env python3
"""Generate a stub com.morningmission.app.R for offline javac type-checking.

The real R.java is produced by AGP at build time from res/. The Android SDK
is not available in every environment (tools/check.sh explains why), so this
walks res/ and emits the same field names with placeholder ids.

Never hand-edit the generated file: resources are added and removed by
ordinary commits, and a stale stub hides both a missing resource and a
reference to a deleted one.
"""
import os, re, sys, xml.etree.ElementTree as ET

# res/<dir>/<file> -> R.<type>.<basename>
DIR_TYPES = ("drawable", "mipmap", "layout", "raw", "font", "anim", "animator",
             "menu", "xml", "color", "transition")
# <resources><item-tag name="..."> -> R.<type>.<name>
VALUE_TAGS = {"color": "color", "string": "string", "style": "style",
              "dimen": "dimen", "integer": "integer", "bool": "bool",
              "string-array": "array", "integer-array": "array", "array": "array",
              "attr": "attr", "plurals": "plurals", "fraction": "fraction"}


def scan(res_dir):
    found = {}
    for entry in sorted(os.listdir(res_dir)):
        path = os.path.join(res_dir, entry)
        if not os.path.isdir(path):
            continue
        kind = entry.split("-", 1)[0]          # "drawable-nodpi" -> "drawable"
        if kind in DIR_TYPES:
            for f in sorted(os.listdir(path)):
                if f.startswith("."):
                    continue
                # strip .9.png before .png so nine-patches keep their name
                name = re.sub(r"\.9\.png$|\.[^.]+$", "", f)
                found.setdefault(kind, set()).add(name)
        if kind == "values":
            for f in sorted(os.listdir(path)):
                if not f.endswith(".xml"):
                    continue
                try:
                    root = ET.parse(os.path.join(path, f)).getroot()
                except ET.ParseError as e:
                    sys.exit("genrstub: %s/%s is not valid XML: %s" % (entry, f, e))
                for child in root:
                    tag = child.tag
                    if tag == "item":
                        tag = child.get("type") or "item"
                    kind2 = VALUE_TAGS.get(tag)
                    name = child.get("name")
                    if kind2 and name:
                        found.setdefault(kind2, set()).add(name.replace(".", "_"))
    return found


def main():
    if len(sys.argv) != 3:
        sys.exit("usage: genrstub.py <res-dir> <out-file>")
    res_dir, out = sys.argv[1], sys.argv[2]
    found = scan(res_dir)
    lines = ["// GENERATED by tools/genrstub.py -- do not edit, do not commit.",
             "package com.morningmission.app;",
             "public final class R {"]
    n, ident = 0, 0x7f010000
    for kind in sorted(found):
        lines.append("    public static final class %s {" % kind)
        for name in sorted(found[kind]):
            ident += 1
            n += 1
            lines.append("        public static final int %s=0x%x;" % (name, ident))
        lines.append("    }")
    lines.append("}")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("genrstub: %d resources in %d types -> %s" % (n, len(found), out))


if __name__ == "__main__":
    main()
